# conf/config.yaml
defaults:
  - _self_
  - net: default

seed: 42

net:
  depth: 3
  width: 32
  num_classes: 10

trainer:
  max_epochs: 10
  log_every_n_steps: 10

dataset:
  batch_size: 1024
  train_size: 0.8

wandb:
  entity: "mamiglia"
  project: "fds-mnist"
  name: ${net.depth}x${net.width}
