# conf/config.yaml
defaults:
  - _self_
  - net: lenet

seed: 42

trainer:
  max_epochs: 10
  log_every_n_steps: 10

dataset:
  batch_size: 256
  val_ratio: 0.2
  num_workers: 4
  seed: ${seed}


wandb:
  entity: "mamiglia"
  project: "fds-mnist"
  name: ${net.depth}x${net.width}
